# -*- coding: utf-8 -*-
"""Healthy Lifestyle Detection using RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DjWkCV6XHBgi9-aexK_DS7DYUXZh6Icl
"""

#    Healthy Lifestyle Detection using RNN

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
from tensorflow.keras.optimizers import Adam

#   Generate synthetic data
np.random.seed(42)
data_size = 5000

sleep_hours = np.random.normal(7, 1.5, data_size).clip(3, 12)
calorie_intake = np.random.normal(2200, 400, data_size).clip(1000, 4000)
exercise_minutes = np.random.normal(35, 20, data_size).clip(0, 120)
water_liters = np.random.normal(2, 0.6, data_size).clip(0.5, 4)
steps_count = np.random.normal(8000, 3000, data_size).clip(500, 20000)

#   Label generation (Healthy = 1 / Unhealthy = 0)
healthy_label = (
    (sleep_hours >= 6) & (sleep_hours <= 9) &
    (1600 <= calorie_intake) & (calorie_intake <= 2600) &
    (exercise_minutes >= 30) &
    (water_liters >= 1.5) &
    (steps_count >= 6000)
).astype(int)

df = pd.DataFrame({
    "sleep_hours": sleep_hours,
    "calorie_intake": calorie_intake,
    "exercise_minutes": exercise_minutes,
    "water_liters": water_liters,
    "steps_count": steps_count,
    "healthy_lifestyle": healthy_label
})

df.to_csv("healthy_lifestyle_dataset.csv", index=False)
print("✔ Dataset generated & saved as healthy_lifestyle_dataset.csv")



#    DATA PREPROCESSING & NORMALIZATION


data = pd.read_csv("healthy_lifestyle_dataset.csv")

X = data.drop("healthy_lifestyle", axis=1).values
y = data["healthy_lifestyle"].values

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

#     RNN expects sequential shape (samples, time_steps, features)
X_scaled = X_scaled.reshape(X_scaled.shape[0], X_scaled.shape[1], 1)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)


#    RNN MODEL DEVELOPMENT  (Model Creation)


model = Sequential([
    SimpleRNN(32, return_sequences=True, input_shape=(5,1)),
    SimpleRNN(16),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print(model.summary())



#    MODEL TRAINING & EVALUATION


history = model.fit(
    X_train, y_train,
    epochs=40,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

loss, acc = model.evaluate(X_test, y_test)
print(f"\n🔥 Test Accuracy = {acc*100:.2f}%")

y_pred = (model.predict(X_test) > 0.5).astype(int)

print("\n📌 Classification Report:\n", classification_report(y_test, y_pred))


acc = history.history['accuracy']
val_acc = history.history['val_accuracy']


#   Model starts stabilizing around epoch
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

for i in range(2, len(acc)):
    if abs(acc[i] - acc[i-1]) < 0.001 and abs(val_acc[i] - val_acc[i-1]) < 0.001:
        print(f"Model may be stable starting around epoch {i+1}")
        break


                      #VISUAL PERFORMANCE ANALYSIS


#   Confusion matrix + Accuracy/Loss graphs


cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap="Blues")
plt.title("Confusion Matrix")
plt.show()

epochs = range(1, len(history.history['accuracy'])+1)

plt.plot(epochs, history.history['accuracy'], label="Train Accuracy")
plt.plot(epochs, history.history['val_accuracy'], label="Validation Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Accuracy Progression")
plt.legend()
plt.show()

plt.plot(epochs, history.history['loss'], label="Train Loss")
plt.plot(epochs, history.history['val_loss'], label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Loss Progression")
plt.legend()
plt.show()